Mvvm
AndroidDevoper/RickAndMorty pull request #3
Opened 2024-06-02 13:01 UTC by SergeyDerkachev

2024-06-04 08:28 UTC, AndroidDevoper requested changes

2024-06-04 08:28 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterAdapter.kt
> +    class Comparator : DiffUtil.ItemCallback<CharacterVo>() {
Отступы между классами и методами

2024-06-04 08:28 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterAdapter.kt
> +        val view = LayoutInflater.from(parent.context)
Можешь попробовать тут сделать binding(как во фрагменте) и передать его в Holder

2024-06-04 08:28 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterAdapter.kt
> +            view.findNavController().navigate(R.id.fullCharacterFragment)
Передай callback во фрагмент, пускай он занимается навигацией

2024-06-04 08:28 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/remote/CharacterRepository.kt
> +                name = dto.name ?: "",
Не нужно переделывать, для общего развития: можно использовать .orEmpty()
or - или
empty - пусто

2024-06-04 08:28 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +        binding.listCharacter.layoutManager = LinearLayoutManager(requireContext())
layoutManager можно в xml проставлять

2024-06-04 08:28 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +        viewModel.characters.observe(viewLifecycleOwner, Observer { characters ->
Можно записать 
viewModel.characters.observe(viewLifecycleOwner) { characters ->

}

2024-06-04 08:28 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/characters/FullCharacterFragment.kt
> +class FullCharacterFragment : Fragment() {
Обычно так обзываем
CharacterDetailsFragment

2024-06-04 08:29 UTC, AndroidDevoper commented
![image](https://github.com/AndroidDevoper/RickAndMorty/assets/82339552/fbcd0cdf-5b6b-4f9c-8bfb-f5bd4792c567)

Баг если пролистать в самый низ

2024-06-04 08:32 UTC, AndroidDevoper commented
Задание со звездочкой)
Если отключить интернет и включить приложение то будет краш
Нужно исправить + добавь сообщение Snackbar "Нет интернета"

2024-06-04 08:35 UTC, AndroidDevoper commented
Давай везде где идет загрузка, использовать ProgressBar по центру

2024-06-05 13:09 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterAdapter.kt
> +    class Comparator : DiffUtil.ItemCallback<CharacterVo>() {
Готово

2024-06-05 13:17 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterAdapter.kt
> +        val view = LayoutInflater.from(parent.context)
Адаптер переделал

2024-06-05 13:17 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterAdapter.kt
> +            view.findNavController().navigate(R.id.fullCharacterFragment)
Адаптер переделал

2024-06-05 13:18 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/remote/CharacterRepository.kt
> +                name = dto.name ?: "",
Ок

2024-06-05 13:26 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +        binding.listCharacter.layoutManager = LinearLayoutManager(requireContext())
Ок

2024-06-05 13:30 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +        viewModel.characters.observe(viewLifecycleOwner, Observer { characters ->
Готово

2024-06-05 13:35 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/characters/FullCharacterFragment.kt
> +class FullCharacterFragment : Fragment() {
Исправлено

2024-06-06 12:01 UTC, SergeyDerkachev commented
Готово

2024-08-18 11:36 UTC, closed without merging