Noinet
AndroidDevoper/RickAndMorty pull request #4
Opened 2024-06-06 12:12 UTC by SergeyDerkachev

2024-06-10 21:35 UTC, AndroidDevoper requested changes

2024-06-10 21:35 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterAdapter.kt
> +                it.findNavController().navigate(R.id.fullCharacterFragment, bundle)
Не так понял
Нужно что-бы по клику этот код:
`val bundle = Bundle().apply {
                    putInt("characterId", character.id)
                }
it.findNavController().navigate(R.id.fullCharacterFragment, bundle)`
Выполнялся в CharactersFragment

2024-06-10 21:35 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersViewModel.kt
> +    val characters = liveData(Dispatchers.IO) {
Достаточно реализовать 
try {
    val retrievedCharacters = characterRepository.getCharacters()
    emit(retrievedCharacters)
} catch (e: Exception) {
    emit(emptyList())
}

То есть characterRepository.getCharacters() этот метод сам вызывает throw если нет интернета, дополнительная проверка и throw IOException не нужны
Можно оставить 1 catch потому что IOException наследуется у Exception

2024-06-11 06:48 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersViewModel.kt
> +    val characters = liveData(Dispatchers.IO) {
Исправил

2024-06-11 07:58 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterAdapter.kt
> +                it.findNavController().navigate(R.id.fullCharacterFragment, bundle)
Сделал

2024-06-13 18:39 UTC, AndroidDevoper approved these changes

2024-06-13 18:39 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/remote/NetworkUtil.kt
> +        val connectivityManager = context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
На будущее
Можно использовать getSystemService(ConnectivityManager::class.java)

2024-06-13 18:39 UTC, merged

2024-06-14 06:46 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/remote/NetworkUtil.kt
> +        val connectivityManager = context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
Понятно