Detail and Paging
AndroidDevoper/RickAndMorty pull request #6
Opened 2024-06-18 11:34 UTC by SergeyDerkachev

2024-06-19 15:08 UTC, AndroidDevoper requested changes

2024-06-19 15:08 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterDetailAdapter.kt
> +    private val items = mutableListOf<Any>()
Чтобы не использовать Any, для таких случаев eсть sealed class CharacterDetailRecyclerItem
В нем сделать CharacterDetailInfoRecyclerItem(character: CharacterVo)
И CharacterDetailLocationRecyclerItem(location: Location)

Хоть он тут и не обязателен, но мне больше нравиться везде использовать ListAdapter

2024-06-19 15:08 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/viewholders/CharacterDetailHolder.kt
> +    override fun bind(item: CharacterVo) {
Не забывай про отступы

2024-06-19 15:08 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/viewholders/CharacterDetailHolder.kt
> +        binding.characterName.text = item.name
Чтобы много раз не писать binding, можно использовать with(binding) { ... } или binding.run { ... }

2024-06-19 15:08 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharacterDetailsFragment.kt
> +    private lateinit var adapter: CharacterDetailAdapter
lateinit var сейчас в разработке используют очень осторожно, пытаются обойтись без него
Выносить из метода onViewCreated тут вроде не обязательно, на крайний случай можешь прям тут сделать = CharacterDetailAdapter()

2024-06-19 15:08 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +            binding.progressBar.visibility = if (isLoading) View.VISIBLE else View.GONE
Вот это правильно, что вынес обработку

2024-06-19 15:08 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +                    visibleItemCount + firstVisibleItemPosition >= totalItemCount &&
Тут конечно без стопки не разберешься, что происходит)

Для пагинации используют готовый PagingDataAdapter https://habr.com/ru/articles/682120/
Он сложноват в первоначальной настройки, но он надежнее
Если хочешь, можешь попробовать

2024-06-19 15:08 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersViewModel.kt
> +    val loading: LiveData<Boolean> get() = _loading
То же правильный подход, что публичным делать LiveData а не MutableLiveData

2024-06-19 15:08 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersViewModel.kt
> +                    CharacterVo(
Пускай репозиторий возращает CharacterVo

2024-06-21 10:25 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterDetailAdapter.kt
> +    private val items = mutableListOf<Any>()
Готово

2024-06-21 10:26 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/viewholders/CharacterDetailHolder.kt
> +    override fun bind(item: CharacterVo) {
Ок

2024-06-21 10:38 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/viewholders/CharacterDetailHolder.kt
> +        binding.characterName.text = item.name
Ок. Готово

2024-06-21 10:45 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharacterDetailsFragment.kt
> +    private lateinit var adapter: CharacterDetailAdapter
Готово

2024-06-21 10:48 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +            binding.progressBar.visibility = if (isLoading) View.VISIBLE else View.GONE
Ок

2024-06-21 11:07 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +                    visibleItemCount + firstVisibleItemPosition >= totalItemCount &&
Попозже. Сейчас попробовал. Запутался.

2024-06-21 11:22 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersViewModel.kt
> +    val loading: LiveData<Boolean> get() = _loading
Ок

2024-06-21 11:45 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersViewModel.kt
> +                    CharacterVo(
Готово

2024-06-24 20:47 UTC, AndroidDevoper approved these changes

2024-06-24 20:47 UTC, merged