Favorites
AndroidDevoper/RickAndMorty pull request #7
Opened 2024-08-02 11:46 UTC by SergeyDerkachev

2024-08-07 10:40 UTC, AndroidDevoper requested changes

2024-08-07 10:40 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterAdapter.kt
> +    private val viewModel: FavoritesViewModel,
Так нельзя
Получается большая связность, например у тебя не получится переиспользовать этот адаптер на других экранах, так как там будут другие viewModel
У тебя должны готовые элементы приходить в адаптер с проставленными фаворитами 
Можешь создать дата класс CharacterAdapterItem, поставить в ListAdapter в него положить CharacterVo и isFavorite

2024-08-07 10:40 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterAdapter.kt
> +                    toggleFavorite(character)
по аналогии с clickListener нужно передавать во viewModel, а он будет в адаптер обновленный список передавать

2024-08-07 10:40 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterDetailAdapter.kt
>      fun setData(character: CharacterVo) {
C ListAdapter этот метод не нужен, нужно использовать только submitList из фрагмента, а viewModel пускай сразу сделает add

2024-08-07 10:40 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterDetailAdapter.kt
> +class CharacterDetailAdapter (private val repository: CharacterRepository): ListAdapter<CharacterDetailRecyclerItem,
repository то же сюда нельзя, вся логика должна быть во viewModel, у адаптера только одна цель - отрисовать

2024-08-07 10:40 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/remote/CharacterRepository.kt
> +        withContext(Dispatchers.IO) {
Ретрофит и рум под капотом имеют реализацию withContext(Dispatchers.IO), нет необходимости еще раз ставить 
Везде пройдись удали

2024-08-07 10:40 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/remote/favorite/FavoriteCharacter.kt
> +data class FavoriteCharacter(
Лучше назвать просто CharacterEntity
Так как по сути это та же схема что и персонаж, и в будущем можно будет сохранять не только как фаворита

2024-08-07 10:40 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/remote/favorite/FavoriteCharacter.kt
> +    val name: String,
Поля как в dto должны быть нулабельны, связанно с тем, что версии баз данных могут обновятся, и какое нибудь поле затрется, что приведет к крашу

2024-08-07 10:40 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/viewholders/CharacterDetailHolder.kt
> +    private val repository: CharacterRepository
Аналогично убрать репозиторий

2024-08-07 10:40 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharacterDetailsFragment.kt
> +        repository = CharacterRepository(requireContext())
Только во viewModel оставь

2024-08-07 10:40 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +    private val favoritesViewModel: FavoritesViewModel by viewModels {
Оставь только CharactersViewModel

2024-08-07 10:40 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/favorites/FavoritesViewModel.kt
> +            val favorites = withContext(Dispatchers.IO) {
Тут то же нет необходимости в Dispatchers.IO

2024-08-07 13:08 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/remote/CharacterRepository.kt
> +        withContext(Dispatchers.IO) {
Удалил

2024-08-07 13:10 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/remote/favorite/FavoriteCharacter.kt
> +    val name: String,
Готово

2024-08-08 05:19 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterAdapter.kt
> +    private val viewModel: FavoritesViewModel,
Готово

2024-08-08 05:21 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterAdapter.kt
> +                    toggleFavorite(character)
Готово

2024-08-08 06:22 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterDetailAdapter.kt
>      fun setData(character: CharacterVo) {
Готово

2024-08-09 06:40 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/favorites/FavoritesViewModel.kt
> +            val favorites = withContext(Dispatchers.IO) {
Готово

2024-08-09 08:39 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +    private val favoritesViewModel: FavoritesViewModel by viewModels {
готово

2024-08-09 12:07 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterDetailAdapter.kt
> +class CharacterDetailAdapter (private val repository: CharacterRepository): ListAdapter<CharacterDetailRecyclerItem,
Готово

2024-08-09 12:18 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/viewholders/CharacterDetailHolder.kt
> +    private val repository: CharacterRepository
Готово

2024-08-09 12:23 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharacterDetailsFragment.kt
> +        repository = CharacterRepository(requireContext())
Готово

2024-08-09 12:29 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/favorites/FavoritesViewModel.kt
> +            val favorites = withContext(Dispatchers.IO) {
Если убрать. Краш.

2024-08-12 20:54 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterDetailAdapter.kt
> +            return oldItem == newItem
Немного теории)
Зачем нужен DiffUtil.ItemCallback?
Он нужен, чтобы если в List<CharacterDetailRecyclerItem> изменился только один элемент, найти его в адаптере и перерисовать только его, а не все карточки
Сначала идет быстрая проверка в методе areItemsTheSame(), чтобы найти старый элемент, обычно тут по id смотрят
Потом метод areContentsTheSame, тут уже полноценно сверяются содержимое элементов, и если содержимое разное, то вызовется onCreateViewHolder и перерисует этот элемент

2024-08-12 20:54 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/remote/CharacterRepository.kt
> +    private fun String?.orEmpty() = this ?: ""
Хороший способ, но в языке котлин уже есть такой)

2024-08-12 20:54 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/remote/CharacterRepository.kt
> +    private fun List<String>?.orEmptyList() = this ?: emptyList()
Такое то же есть)
.orEmpty()

2024-08-12 20:54 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +            updateCharacterList()
Оставь одну LiveData c List CharacterAdapterItem и все манипуляции делай во viewModel

2024-08-12 20:54 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +                    viewModel.removeFavoriteCharacter(item.character.id)
Логика должна быть во viewModel - viewModel.onFavoriteCharacterClicked(item)

2024-08-12 20:54 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/data/viewholders/CharacterDetailHolder.kt
> +    private val repository: CharacterRepository
Его в классе не должно быть, Holder относится к UI, он не должен работать с БД

2024-08-12 21:03 UTC, AndroidDevoper commented
Можешь поэксперментировать, если найдешь применение - в FavoriteDao добавить метод getAllFavoritesLiveData(): LiveData
Ты сможешь подписаться и следить за обновлениями, после методов insert или delete список автоматичеки будет обновляться

2024-08-12 21:03 UTC, AndroidDevoper requested changes

2024-08-12 21:03 UTC, AndroidDevoper commented on app/src/main/java/com/example/rickandmorty/ui/favorites/FavoritesFragment.kt
> +                val updatedList = charactersAdapter.currentList.toMutableList().apply {
Мне проще было бы использовать map {
    if (item == it) item.copy(isFavorite = !item.isFavorite) else it
}
То есть делаем новый список из старых элементов, но если item по которому кликнули равен старому элементу, то обновляем через copy

2024-08-13 05:28 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/remote/CharacterRepository.kt
> +    private fun String?.orEmpty() = this ?: ""
Исправил

2024-08-13 05:28 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/remote/CharacterRepository.kt
> +    private fun List<String>?.orEmptyList() = this ?: emptyList()
Исправил

2024-08-13 06:13 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +            updateCharacterList()
Готово

2024-08-13 06:26 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/characters/CharactersFragment.kt
> +                    viewModel.removeFavoriteCharacter(item.character.id)
Сделал

2024-08-13 12:15 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/adapter/CharacterDetailAdapter.kt
> +            return oldItem == newItem
Сделал  oldItem.character.id == newItem.character.id

2024-08-13 12:55 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/ui/favorites/FavoritesFragment.kt
> +                val updatedList = charactersAdapter.currentList.toMutableList().apply {
Да. Лучше. Переделал.

2024-08-18 11:02 UTC, AndroidDevoper approved these changes

2024-08-18 11:05 UTC, merged

2024-08-18 11:33 UTC, SergeyDerkachev commented on app/src/main/java/com/example/rickandmorty/data/viewholders/CharacterDetailHolder.kt
> +    private val repository: CharacterRepository
Сделал